version: '2'
services:
  kibana:
    image: kibana:6.5.1
    container_name: kibana
    hostname: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - /Users/zhongjun/projects/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      es_kibana:
        ipv4_address: 172.25.10.10
  elasticsearch:
    image: elasticsearch:6.5.1
    container_name: elasticsearch
    hostname: es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - DISCOVERY_TYPE=single-node
    networks:
      es_kibana:
        ipv4_address: 172.25.10.11

networks:
  es_kibana:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
