cluster.name: es-cluster 
node.name: node-master
node.master: true
node.data: true
http.port: 9200
network.host: 0.0.0.0
network.publish_host: 172.25.10.11 
discovery.zen.ping.unicast.hosts: ["172.25.10.11:9300"]
discovery.zen.minimum_master_nodes: 1
